//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReferralManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RewardPlan
    {
        public int PlanID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int ReferralRewardType { get; set; }
        public int ReferralRewardValue { get; set; }
        public int Valid { get; set; }
        public int ReferredRewardType { get; set; }
        public int ReferredRewardValue { get; set; }
        public string CouponName { get; set; }
        public string CouponDescription { get; set; }
    }
}
