//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReferralManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public Nullable<int> ReferedBy { get; set; }
        public Nullable<double> TotalReward { get; set; }
        public Nullable<double> AvialableReward { get; set; }
        public Nullable<int> RewardPlan { get; set; }
        public string ReferLink { get; set; }
        public Nullable<int> PhoneNum { get; set; }
        public Nullable<int> NumReferred { get; set; }
        public string ReferCode { get; set; }
    }
}
